#!/bin/bash
# Quick start guide for 3 clients

echo "=========================================="
echo "3 Clients Setup - Quick Start"
echo "=========================================="
echo ""
echo "✅ Clients Registered:"
echo "  • Alice → test1.jpeg"
echo "  • Bob → test2.jpeg"
echo "  • Charlie → test3.jpeg"
echo ""
echo "🚀 Start Heartbeats in 3 Terminals:"
echo ""
echo "TERMINAL 1 (Alice):"
echo "  cd $(pwd)"
echo "  ./client/target/release/p2p-client start-heartbeat \\"
echo "    --username alice --ip 192.168.1.10 --port 6000 --interval 5"
echo ""
echo "TERMINAL 2 (Bob):"
echo "  cd $(pwd)"
echo "  ./client/target/release/p2p-client start-heartbeat \\"
echo "    --username bob --ip 192.168.1.20 --port 6001 --interval 5"
echo ""
echo "TERMINAL 3 (Charlie):"
echo "  cd $(pwd)"
echo "  ./client/target/release/p2p-client start-heartbeat \\"
echo "    --username charlie --ip 192.168.1.30 --port 6002 --interval 5"
echo ""
echo "📡 Test Discovery (after heartbeats start):"
echo "  ./client/target/release/p2p-client list-online"
echo ""
echo "Or with curl:"
echo "  curl http://localhost:8000/discovery/online | jq"
echo ""
echo "Expected: Shows username, IP, port, and image preview!"
echo ""

